services:
  - type: web
    name: aiinventoryapp
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn inventory_system.wsgi:application
    postDeployCommand: python manage.py migrate --noinput
