services:
  - type: web
    runtime: python
    name: aiinventoryapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn aiinventory.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-render-db-name
          property: connectionString
    postDeployScript: |
      python manage.py migrate
